
mysql:
    image: daocloud.io/koolay/alpine-mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/opt/data
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf

redis:
    image: daocloud.io/koolay/alpine-redis:latest
    ports:
      - "6378:6379"

nginx:
    image: daocloud.io/koolay/alpine-nginx:latest
    ports:
      - "8080:8080"
    links:
      - "fpm"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./app:/app

fpm:
    image: daocloud.io/koolay/alpine-php:latest
    #ports: #这里不需要暴露
    #  - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
     - ./php/conf/php-fpm.conf:/etc/php/php-fpm.conf
     - ./php/conf/php.ini:/etc/php/php.ini
     - ./php/conf/pool.d/www.conf:/etc/php/fpm/pool.d/www.conf
     - ./app:/app

