
#mysql:
#    build: ./mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/data:/var/lib/mysql
#      

#redis:
#    build: ./redis
#    ports:
#      - "6378:6379"

nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    links:
      - "fpm"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./app:/app

fpm:
    build: ./php
    #ports:
    #  - "9000:9000"
    #links:
    #  - "mysql"
    #  - "redis"
    volumes:
     - ./php/conf/php-fpm.conf:/etc/php/php-fpm.conf
     - ./php/conf/php.ini:/etc/php/php.ini
     - ./php/conf/pool.d/www.conf:/etc/php/fpm/pool.d/www.conf
     - ./app:/app

