
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
#  environment:
#      MYSQL_ROOT_PASSWORD: 123456

redis:
    build: ./redis
    ports:
      - "6378:6379"

nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    links:
      - "php"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/app:/app

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ./php/conf:/etc/php

